### ISSUE TITLE
WSL validation fails if no distributions are installed

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno.check#11]
Using the --preview option with the system configured in Spanish:

Checkup had Error status: wsl

wsl: Could not find color or style 'Argumento'.
! There were one or more problems detected.
Please review the errors and correct them and run uno-check again.

![image](https://user-images.githubusercontent.com/3109851/131667460-1dab6ae7-b5f0-4f77-a86f-6fa22633db41.png)

I'll change the system language to English to see if it has something to do with it.

**Comment by SuperJMN** [comment]
OK, in US English, the problem persists.

![image](https://user-images.githubusercontent.com/3109851/131669138-8de3f7c6-4536-41f3-97f6-dcbec2e438f1.png)

**Comment by jeromelaban** [comment]
Thanks for the report.

**Comment by jeromelaban** [comment]
Can you paste the full log? There's an exception stack trace above.

**Comment by SuperJMN** [comment]
Full log :D

```
PowerShell 7.1.4
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\JMN> uno-check.exe --preview --verbose

 
           ╔╣╝"╚╬╗
         ╔╣`     "╣╗
       ,@Ñ╝╩╬╗     ╚▒Ñ%,
     ╔╬╝     ]╣╦   ╔▓  ╚╣╗
    ╬╝     ,@╝  ╚@╬╝     ▒
    ╬╗   ,╣╝ ╝@╦╣`     ╔╣╝
     ╚╬╦ ▒     ╚@╗   ╔╣╝
        ╚╝@      "╚╣▒
           ╚h    ,@╝
             ╚Ñ@Ñ╝
 

                                         _                     _
  _   _   _ __     ___             ___  | |__     ___    ___  | | __
 | | | | | '_ \   / _ \   _____   / __| | '_ \   / _ \  / __| | |/ /
 | |_| | | | | | | (_) | |_____| | (__  | | | | |  __/ | (__  |   <
  \__,_| |_| |_|  \___/           \___| |_| |_|  \___|  \___| |_|\_\

¤ Uno Platform Check v1.0.0.0 ¤
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────This tool will check your Uno Platform development environment.
If problems are detected, it will offer the option to try and fix them for you, or suggest a way to fix them yourself.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────» Synchronizing configuration...Loading Manifest from: https://raw.githubusercontent.com/unoplatform/uno.check/main/manifests/uno.ui-preview.manifest.json
Required Version: 0.6.1
Current Version: 1.0.0.0
 ok
» Scheduling appointments...SetEnvironmentVariable: DOTNET_ROOT=C:\Program Files\dotnet
SetEnvironmentVariable: DOTNET_ROOT=C:\Program Files\dotnet
 ok

> OpenJDK 11.0 Checkup...
ValidateAndroidSdkLocation: ``, result=False
ValidateAndroidSdkLocation: ``, result=False
Looking for Android SDK...
ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True
ValidateJavaSdkLocation: ``, result=False
ValidateJavaSdkLocation: ``, result=False
ValidateJavaSdkLocation: `C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot`, result=True
ValidateAndroidNdkLocation: ``, result=False
ValidateAndroidNdkLocation: ``, result=False
Looking for Android NDK...
Looking for Android SDK...
SHELL: C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\javac.exe -version
javac 11.0.10
SHELL: C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\javac.exe -version
javac 1.8.0-25
SHELL: C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\javac.exe -version
javac 11.0.10
  - 11.0.10 (C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\..)
SetEnvironmentVariable: JAVA_HOME=C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot
  - 1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)

> Visual Studio 17.0.0-pre.2.0 Checkup...
SHELL: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -all -requires Microsoft.Component.MSBuild  -format json -prerelease
[
  {
    "instanceId": "3e5e6af5",
    "installDate": "2021-08-23T19:25:37Z",
    "installationName": "VisualStudioPreview/17.0.0-pre.3.1+31612.314",
    "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview",
    "installationVersion": "17.0.31612.314",
    "productId": "Microsoft.VisualStudio.Product.Enterprise",
    "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe",
    "state": 4294967295,
    "isComplete": true,
    "isLaunchable": true,
    "isPrerelease": true,
    "isRebootRequired": false,
    "displayName": "Visual Studio Enterprise 2022",
    "description": "Scalable, end-to-end solution for teams of any size",
    "channelId": "VisualStudio.17.Preview",
    "channelUri": "https://aka.ms/vs/17/pre/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=661273#17.0.0-pre.3.1",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
    "updateDate": "2021-08-23T19:25:37.4331372Z",
    "catalog": {
      "buildBranch": "d17.0",
      "buildVersion": "17.0.31612.314",
      "id": "VisualStudioPreview/17.0.0-pre.3.1+31612.314",
      "localBuild": "build-lab",
      "manifestName": "VisualStudioPreview",
      "manifestType": "installer",
      "productDisplayVersion": "17.0.0 Preview 3.1",
      "productLine": "Dev17",
      "productLineVersion": "2022",
      "productMilestone": "Preview",
      "productMilestoneIsPreRelease": "True",
      "productName": "Visual Studio",
      "productPatchVersion": "0",
      "productPreReleaseMilestoneSuffix": "3.1",
      "productSemanticVersion": "17.0.0-pre.3.1+31612.314",
      "requiredEngineVersion": "3.0.2333.53618"
    },
    "properties": {
      "campaignId": "1674212678.1629746607",
      "channelManifestId": "VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
    }
  }
]
  - 17.0.0-pre.3.1 - C:\Program Files\Microsoft Visual Studio\2022\Preview

> Visual Studio Workloads Checkup...
SHELL: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -all -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Workload.Universal -format json -prerelease
[
  {
    "instanceId": "3e5e6af5",
    "installDate": "2021-08-23T19:25:37Z",
    "installationName": "VisualStudioPreview/17.0.0-pre.3.1+31612.314",
    "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview",
    "installationVersion": "17.0.31612.314",
    "productId": "Microsoft.VisualStudio.Product.Enterprise",
    "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe",
    "state": 4294967295,
    "isComplete": true,
    "isLaunchable": true,
    "isPrerelease": true,
    "isRebootRequired": false,
    "displayName": "Visual Studio Enterprise 2022",
    "description": "Scalable, end-to-end solution for teams of any size",
    "channelId": "VisualStudio.17.Preview",
    "channelUri": "https://aka.ms/vs/17/pre/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=661273#17.0.0-pre.3.1",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
    "updateDate": "2021-08-23T19:25:37.4331372Z",
    "catalog": {
      "buildBranch": "d17.0",
      "buildVersion": "17.0.31612.314",
      "id": "VisualStudioPreview/17.0.0-pre.3.1+31612.314",
      "localBuild": "build-lab",
      "manifestName": "VisualStudioPreview",
      "manifestType": "installer",
      "productDisplayVersion": "17.0.0 Preview 3.1",
      "productLine": "Dev17",
      "productLineVersion": "2022",
      "productMilestone": "Preview",
      "productMilestoneIsPreRelease": "True",
      "productName": "Visual Studio",
      "productPatchVersion": "0",
      "productPreReleaseMilestoneSuffix": "3.1",
      "productSemanticVersion": "17.0.0-pre.3.1+31612.314",
      "requiredEngineVersion": "3.0.2333.53618"
    },
    "properties": {
      "campaignId": "1674212678.1629746607",
      "channelManifestId": "VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
    }
  }
]
  - Universal Windows Platform development is installed (17.0.0-pre.3.1)
SHELL: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -all -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Workload.NetCrossPlat -format json -prerelease
[
  {
    "instanceId": "3e5e6af5",
    "installDate": "2021-08-23T19:25:37Z",
    "installationName": "VisualStudioPreview/17.0.0-pre.3.1+31612.314",
    "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview",
    "installationVersion": "17.0.31612.314",
    "productId": "Microsoft.VisualStudio.Product.Enterprise",
    "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe",
    "state": 4294967295,
    "isComplete": true,
    "isLaunchable": true,
    "isPrerelease": true,
    "isRebootRequired": false,
    "displayName": "Visual Studio Enterprise 2022",
    "description": "Scalable, end-to-end solution for teams of any size",
    "channelId": "VisualStudio.17.Preview",
    "channelUri": "https://aka.ms/vs/17/pre/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=661273#17.0.0-pre.3.1",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
    "updateDate": "2021-08-23T19:25:37.4331372Z",
    "catalog": {
      "buildBranch": "d17.0",
      "buildVersion": "17.0.31612.314",
      "id": "VisualStudioPreview/17.0.0-pre.3.1+31612.314",
      "localBuild": "build-lab",
      "manifestName": "VisualStudioPreview",
      "manifestType": "installer",
      "productDisplayVersion": "17.0.0 Preview 3.1",
      "productLine": "Dev17",
      "productLineVersion": "2022",
      "productMilestone": "Preview",
      "productMilestoneIsPreRelease": "True",
      "productName": "Visual Studio",
      "productPatchVersion": "0",
      "productPreReleaseMilestoneSuffix": "3.1",
      "productSemanticVersion": "17.0.0-pre.3.1+31612.314",
      "requiredEngineVersion": "3.0.2333.53618"
    },
    "properties": {
      "campaignId": "1674212678.1629746607",
      "channelManifestId": "VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
    }
  }
]
  - Mobile development with .NET is installed (17.0.0-pre.3.1)
SHELL: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -all -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Workload.NetWeb -format json -prerelease
[
  {
    "instanceId": "3e5e6af5",
    "installDate": "2021-08-23T19:25:37Z",
    "installationName": "VisualStudioPreview/17.0.0-pre.3.1+31612.314",
    "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview",
    "installationVersion": "17.0.31612.314",
    "productId": "Microsoft.VisualStudio.Product.Enterprise",
    "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe",
    "state": 4294967295,
    "isComplete": true,
    "isLaunchable": true,
    "isPrerelease": true,
    "isRebootRequired": false,
    "displayName": "Visual Studio Enterprise 2022",
    "description": "Scalable, end-to-end solution for teams of any size",
    "channelId": "VisualStudio.17.Preview",
    "channelUri": "https://aka.ms/vs/17/pre/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=661273#17.0.0-pre.3.1",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
    "updateDate": "2021-08-23T19:25:37.4331372Z",
    "catalog": {
      "buildBranch": "d17.0",
      "buildVersion": "17.0.31612.314",
      "id": "VisualStudioPreview/17.0.0-pre.3.1+31612.314",
      "localBuild": "build-lab",
      "manifestName": "VisualStudioPreview",
      "manifestType": "installer",
      "productDisplayVersion": "17.0.0 Preview 3.1",
      "productLine": "Dev17",
      "productLineVersion": "2022",
      "productMilestone": "Preview",
      "productMilestoneIsPreRelease": "True",
      "productName": "Visual Studio",
      "productPatchVersion": "0",
      "productPreReleaseMilestoneSuffix": "3.1",
      "productSemanticVersion": "17.0.0-pre.3.1+31612.314",
      "requiredEngineVersion": "3.0.2333.53618"
    },
    "properties": {
      "campaignId": "1674212678.1629746607",
      "channelManifestId": "VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
    }
  }
]
  - ASP.NET and web development is installed (17.0.0-pre.3.1)

> Android SDK Checkup...
ValidateAndroidSdkLocation: ``, result=False
ValidateAndroidSdkLocation: ``, result=False
Looking for Android SDK...
ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True
ValidateJavaSdkLocation: `C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot`, result=True
ValidateAndroidNdkLocation: ``, result=False
ValidateAndroidNdkLocation: ``, result=False
Looking for Android NDK...
Looking for Android SDK...
SetEnvironmentVariable: ANDROID_SDK_ROOT=C:\Program Files (x86)\Android\android-sdk
SetEnvironmentVariable: ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
  - emulator (30.8.4)
  - build-tools;30.0.2 (30.0.2)
  - platforms;android-30 (3)
  - system-images;android-30;google_apis;x86 (10)
  - platform-tools (31.0.3)

> Android Emulator Checkup...
SHELL: C:\Program Files (x86)\Android\android-sdk\tools\bin\avdmanager.bat list device
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
        at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
  ¡ Unable to find any Android Emulators.  You can use Visual Studio to create one if necessary:
https://docs.microsoft.com/xamarin/android/get-started/installation/android-emulator/device-manager
System.Exception: Failed to create android avd
  at DotNetCheck.AndroidSdk.AvdManager.run(Boolean interactive, String[] args) in
     D:\a\uno.check\uno.check\UnoCheck\AndroidSdk\AvdManager.cs:296
  at DotNetCheck.AndroidSdk.AvdManager.ListDevices() in D:\a\uno.check\uno.check\UnoCheck\AndroidSdk\AvdManager.cs:239
  at DotNetCheck.Checkups.AndroidEmulatorCheckup.Examine(SharedState history) in
     D:\a\uno.check\uno.check\UnoCheck\Checkups\AndroidEmulatorCheckup.cs:61

> .NET SDK Checkup...
SetEnvironmentVariable: DOTNET_ROOT=C:\Program Files\dotnet
SHELL: C:\Program Files\dotnet\dotnet.exe --list-sdks
6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  - 6.0.100-preview.6.21355.2 - C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2
  - 6.0.100-preview.7.21379.14 - C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14
SetEnvironmentVariable: DOTNET_SDK=C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2
SetEnvironmentVariable: DOTNET_SDK_VERSION=6.0.100-preview.6.21355.2

> .NET SDK - Workload Deduplication Checkup...
SetEnvironmentVariable: DOTNET_ROOT=C:\Program Files\dotnet

> Edge WebView2 Checkup...
  - Found Edge WebView2 version 92.0.902.84

> Windows Subsystem for Linux Checkup...
SHELL: wsl -l


Copyright (c) Microsoft Corporation. All rights reserved.



Usage: wsl.exe [Argument]



Arguments:



    --install <Options>

        Install Windows Subsystem for Linux features. If no options are specified,

        the recommended features will be installed along with the default distribution.



        To view the default distribution as well as a list of other valid distributions,

        use 'wsl --list --online'.



        Options:

            --distribution, -d [Argument]

                Specifies the distribution to be downloaded and installed by name.



                Arguments:

                    A valid distribution name (not case sensitive).



                Examples:

                    wsl --install -d Ubuntu

                    wsl --install --distribution Debian



    --list, -l [Options]

        Lists distributions.



        Options:

            --online, -o

                Displays a list of available distributions for install with 'wsl --install'.



    --help

        Display usage information.

System.InvalidOperationException: Could not find color or style 'Argument'.
  at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:13
  at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/
     MarkupParser.cs:26
  at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in
     /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:41
  at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, IFormatProvider provider, String format, Object[     ] args) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:31
  at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, IFormatProvider provider, String format,
     Object[] args) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:74
  at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String format, Object[] args) in
     /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:52
  at Spectre.Console.AnsiConsole.MarkupLine(String format, Object[] args) in /_/src/Spectre.Console/
     AnsiConsole.Markup.cs:38
  at DotNetCheck.Cli.CheckCommand.checkupStatusUpdated(Object sender, CheckupStatusEventArgs e) in
     D:\a\uno.check\uno.check\UnoCheck\CheckCommand.cs:313
  at DotNetCheck.Checkups.WSLCheckup.Examine(SharedState history) in D:\a\uno.check\uno.check\UnoCheck\Checkups\
     WSLCheckup.cs:34
  at DotNetCheck.Cli.CheckCommand.ExecuteAsync(CommandContext context, CheckSettings settings) in
     D:\a\uno.check\uno.check\UnoCheck\CheckCommand.cs:161

> .NET SDK - Workloads (6.0.100-preview.6.21355.2) Checkup...
  - microsoft-android-sdk-full (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 30.0.100-preview.6.62) installed.
  - microsoft-ios-sdk-full (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-preview.6.63) installed.
  - microsoft-maccatalyst-sdk-full (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-preview.6.63) installed.
  - microsoft-tvos-sdk-full (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-preview.6.63) installed.
  - microsoft-macos-sdk-full (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-preview.6.63) installed.
  - microsoft-net-runtime-android (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-preview.6.21352.12)
installed.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Checkup had Error status: wsl

wsl: Could not find color or style 'Argument'.
! There were one or more problems detected.
Please review the errors and correct them and run uno-check again.

Press Enter to finish...
```

**Comment by jeromelaban** [comment]
Interesting. Which version of Windows are you running ?

**Comment by SuperJMN** [comment]
![image](https://user-images.githubusercontent.com/3109851/131691393-e018fbd2-5358-4082-a8c5-c9ee28e3dd1d.png)

**Comment by jeromelaban** [comment]
Thanks. It feels like running `-l` when no distributions are installed is causing this. Can you try installing a WSL distribution ?

**Comment by SuperJMN** [comment]
That was the problem. Finishing OK!

![image](https://user-images.githubusercontent.com/3109851/131736921-833834c9-fbb7-4191-af6c-615c28128f48.png)

**Comment by jeromelaban** [comment]
Thanks for the update!

**Comment by jeromelaban** [comment]
This issue can be worked around using `--skip wsl` on the command line.
